{% set name = "elastic" %}
{% set version = "4.0.30.43" %}
{% set sha256 = "a433fb952e67dc3faad699362cc5850092a9fa6a7c16ef8e74d9d176f2cab653" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - future
    - setuptools_scm
    - sphinx
  run:
    - python
    - ase
    - numpy
    - scipy
    - spglib
    - future

test:
  source_files:
    - test
  requires:
    - hypothesis
  imports:
    - elastic
  commands:
    - python -m unittest discover -s test -b 

about:
  home: http://jochym.github.io/Elastic/
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE
  summary: 'Elastic is a set of python routines for calculation of elastic properties of crystals'

  description: |
     Elastic is a set of python routines for calculation of elastic properties 
     of crystals (elastic constants, equation of state, sound velocities, etc.). 
     It is a third version of the code implemented as a extension to the ASE system. 
     The code was a basis for some of my publications and was described briefly 
     in these papers. The code was available to anyone, presented at the Workshop 
     on ab initio Calculations in Geosciences and used by some of my co-workers. 
  doc_url: http://elastic.readthedocs.io/
  dev_url: https://github.com/jochym/elastic

extra:
  recipe-maintainers:
    - jochym
